---
apiVersion: v1
kind: Secret
metadata:
  name: gha-shr-{{ template "github.repoShorthand" }}-{{ .Values.github.repository }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.github.token | b64enc }}
