---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-shr-{{ template "github.repoShorthand" }}-{{ .Values.github.repository }}
  namespace: {{ .Release.Namespace }}
  annotations:
      eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn }}
