misconfigurations:
  - id: AVD-DS-0002
    paths:
      - "containers/daap-*/Dockerfile"
      - "containers/jml-extract-lambda/Dockerfile"
    statement: Regardless of what is specified in the Dockerfile, AWS lambda will run the function as a non-root user. See https://github.com/aws/aws-lambda-dotnet/discussions/1301
