---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
data:
  any: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 4
