---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-device-plugin-daemonset-role-binding
subjects:
  - kind: ServiceAccount
    name: nvidia-device-plugin-daemonset-service-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nvidia-device-plugin-daemonset-role
  apiGroup: rbac.authorization.k8s.io
