---
name: Dependabot configuration generator

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - "**/*.tf"
      - "**/*Dockerfile*"

permissions: read-all

jobs:
  dependabot-configuration-generator:
    name: Dependabot configuration generator
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Run Dependabot configuration generator
        id: generate_configuration
        run: bash -x scripts/dependabot/configuration-generator.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
