---
name: Pull request labeler

on: # yamllint disable-line rule:truthy
  - pull_request_target

permissions: read-all

jobs:
  pull-request-labeler:
    name: Pull request labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Pull request labeler
        id: pull_request_labeler
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
