---
name: 📥 Maintenance - Create JupyterLab Issue

on:
  schedule:
    - cron: "0 8 1 * *" # UTC time: “At 08:00 on first day-of-month”

permissions: {}

jobs:
  create-maintenance-issue:
    name: Create Maintenance Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Maintenance Issue
        id: create_maintenance_issue
        run: |
          if [[ "${CLOSE_PREVIOUS}" == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: 📥 Maintenance - JupyterLab
          ASSIGNEES:
          LABELS: maintenance
          BODY: |
            > [!CAUTION]
            > JupyterLab is still in development. Confirm these updates should be made before proceeding. Delete this caution once JupiterLab is in production.

            ### User Story

            As a… engineer on the Analytical Platform
            I need/want/expect to… keep JupyterLab up to date
            So that… security / best practice etc

            ### Definition of Done
            Since this image relies on the Analytical Platform Cloud Base Development Image ensure that the maintenance issue is completed for that prior to doing this ticket.
            - [ ] Merge any open dependabot Pull Requests in the JupyterLab [repository](https://github.com/ministryofjustice/analytical-platform-jupyterlab).
            - [ ] Create new [release](https://github.com/ministryofjustice/analytical-platform-jupyterlab/releases).
            - [ ] Update [guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/visual-studio-code/#visual-studio-code), if required.
            - [ ] Create a new release in [development](https://controlpanel.services.dev.analytical-platform.service.justice.gov.uk/releases/).
            - [ ] Test deployment in development.
            - [ ] Create a new release in [production](https://controlpanel.services.analytical-platform.service.justice.gov.uk/releases/).
            - [ ] Test deployment in production.

          PINNED: false
          CLOSE_PREVIOUS: false
