---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simulated-data-producer
data:
  entrypoint.sh: |
    #!/bin/sh

    pip install --requirement requirements.txt

    python main.py

  requirements.txt: |
    psycopg2-binary==2.9.5

  main.py: |
    import psycopg2

    DB_ENDPOINT=os.environ.get('DB_ENDPOINT')
    DB_USERNAME=os.environ.get('DB_USERNAME')
    DB_PASSWORD=os.environ.get('DB_PASSWORD')
    DB_NAME=os.environ.get('DB_NAME')

    conn = psycopg2.connect(
        host=DB_ENDPOINT,
        port=5432,
        user=DB_USERNAME,
        password=DB_PASSWORD,
        database=DB_NAME
    )
