---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simulated-data-producer
data:
  entrypoint.sh: |
    #!/bin/sh

    pip install --requirement requirements.txt

    python scripts/simulated-data-producer/main.py

  requirements.txt: |
    requests==2.28.1
    pandas==1.5.3
    SQLAlchemy==2.0.5.post1
    psycopg2-binary==2.9.5
