---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-github-token
  labels:
    {{- include "actions-runner.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.github.token | b64enc }}
