---
title: "Firebreak Summer 2024 Idea Discussion"
body:
- type: markdown
  attributes:
    value: "# Summer 2024 Firebreak Idea Form"
- type: textarea
  attributes:
    label: "## Idea Description\nPlease provide a clear and concise description of your idea."
- type: textarea
  attributes:
    label: "## Why Should We Do This\nExplain why this idea is valuable and should be implemented."
- type: textarea
  attributes:
    label: "## Definition of Done\nWhat criteria should be met for this idea to be considered complete?"
- type: textarea
  attributes:
    label: "## What skills do we need?\nList the skills or expertise required to implement this idea."
- type: textarea
  attributes:
    label: "## Notes\nInclude any additional information or context that would be helpful."
