---
alpine-base: ./containers/alpine-base/**
ubuntu-base: ./containers/ubuntu-base/**
kubectl: ./containers/kubectl/**
daap-athena-load: ./containers/daap-athena-load/**
daap-simulated-data-producer: ./containers/daap-simulated-data-producer/**
rshiny-3.5.3: ./containers/rshiny-3.5.3/**
rshiny-3.6.3: ./containers/rshiny-3.6.3/**
rshiny-4.0.5: ./containers/rshiny-4.0.5/**
rshiny-4.1.3: ./containers/rshiny-4.1.3/**
rshiny-4.2.2: ./containers/rshiny-4.2.2/**
