aws-tools: ./.devcontainer/features/**/aws-tools/**
base: ./.devcontainer/features/**/base/**
cicd-tools: ./.devcontainer/features/**/cicd-tools/**
container-tools: ./.devcontainer/features/**/container-tools/**
git-tools: ./.devcontainer/features/**/git-tools/**
kubernetes-tools: ./.devcontainer/features/**/kubernetes-tools/**
pulumi-tools: ./.devcontainer/features/**/pulumi-tools/**
terraform-tools: ./.devcontainer/features/**/terraform-tools/**
