aws: ./.devcontainer/features/**/aws/**
aws-vault: ./.devcontainer/features/**/aws-vault/**
cosign: ./.devcontainer/features/**/cosign/**
direnv: ./.devcontainer/features/**/direnv/**
flux: ./.devcontainer/features/**/flux/**
git-crypt: ./.devcontainer/features/**/git-crypt/**
helm: ./.devcontainer/features/**/helm/**
kubectl: ./.devcontainer/features/**/kubectl/**
kubelint: ./.devcontainer/features/**/kubelint/**
kubent: ./.devcontainer/features/**/kubent/**
terraform: ./.devcontainer/features/**/terraform/**
