name: Bug Report
description: 🐛 Create a bug report
title: "🐛 <title>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      description: A clear and concise description of what the bug is.
      label: Describe the bug.
      value:
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      description: Steps to reproduce the behaviour.
      label: To Reproduce
      placeholder: 1. Go to '...'

                  2. Click on '....'

                  3. Scroll down to '....'

                  4. See error...
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      description: A clear and concise description of what you expected to happen.
      label: Expected Behaviour
      value:
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      description: Add any other context about the problem here, this could include screenshots for example.
      label: Additional context
      value:
    validations:
      required: false
