name: 🗃️ Data Platform Epic
description: Creates a Data Platform Epic
title: "[gitmoji] <title>"
labels: ["Epic"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the fields below.
  - type: textarea
    id: describe-epic
    attributes:
      label: Brief summary of what this Epic is
      placeholder: "This Epic..."
  - type: textarea
    id: list-issues
    attributes:
      description: List of issues in this epic
      label: List issues in this epic
      value: "- [ ] #1
      
               - [ ] #2 "
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      description: Other information
      label: Other information
      value:
        Slack channel = #data-platform-epic-name
    validations:
      required: false

