name: 📋 Task
description: Create a Task
title: "📋 <title>"
type: "Task"
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Tasks should only be created as children of Stories
  - type: textarea
    id: description
    attributes:
      description: A clear and concise description of the task.
      label: Describe the task.
      value:
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      description: Steps to address the task.
      label: Steps to Address
    validations:
      required: false
