#!/usr/bin/env bash

FEATURE="${1}"

docker build --file .devcontainer/features/test/Dockerfile --tag devcontainer .

devcontainer features test --project-folder .devcontainer/features --features ${FEATURE} --skip-scenarios --base-image devcontainer

devcontainer features test --project-folder .devcontainer/features --features ${FEATURE} --skip-autogenerated --base-image devcontainer
