---
extends: default

ignore:
  # Helm templates
  - '**/charts/*/templates/*.yaml'
  - '**/charts/*/templates/tests/*.yaml'
  - '**/terraform/cloud-platform/live/data-platform-production/github-actions-self-hosted-runners/src/helm/charts/github-actions-self-hosted-runners/templates/*.yml'
  # Kyverno policies
  - '**/terraform/aws/analytical-platform-data-production/airflow/files/kyverno_policies/*'
rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 120
    level: warning
