---
extends: default

ignore:
  # Helm templates
  - terraform/cloud-platform/live/data-platform-production/github-actions-self-hosted-runners/src/helm/charts/github-actions-self-hosted-runners/templates/*.yml

rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 120
    level: warning
