#!/usr/bin/env bash

DEPENDABOT_CONFIGURATION_FILE=".github/dependabot.yml"

echo "Generating ${DEPENDABOT_CONFIGURATION_FILE}"
cat >"${DEPENDABOT_CONFIGURATION_FILE}" <<EOL
---
# This file is auto-generated by running the below command, do not manually amend.
# bash scripts/dependabot/configuration-generator.sh

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    reviewers:
      - "ministryofjustice/data-platform-core-infra"
EOL

for ecosystem in docker pip terraform; do

  echo "=== Ecosystem: ${ecosystem} ==="

  case ${ecosystem} in
    docker)
      SEARCH_PATTERN="*Dockerfile*"
      SKIP_FILE=".dependabot-docker-ignore"
    ;;
    pip)
      SEARCH_PATTERN="*requirements*.txt"
      SKIP_FILE=".dependabot-pip-ignore"
    ;;
    terraform)
      SEARCH_PATTERN=".terraform.lock.hcl"
      SKIP_FILE=".dependabot-terraform-ignore"
    ;;
  esac

  folders=$(find . -type f -name "${SEARCH_PATTERN}" -exec dirname {} \; | sort -h | uniq | cut -c 3-)
  export folders

  echo "=== Folders ==="
  echo "${folders}"

  for folder in ${folders}; do

  if [[ -f "${folder}/${SKIP_FILE}" ]]; then
    echo "Ignoring ${folder}"
    continue
  fi

    printf "  - package-ecosystem: \"%s\"\n" "${ecosystem}" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "    directory: \"%s\"\n" "${folder}" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "    schedule:\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "      interval: \"daily\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "      time: \"09:00\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "      timezone: \"Europe/London\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "    commit-message:\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "      prefix: \"%s\"\n" "${ecosystem}" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "      include: \"scope\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "    reviewers:\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
    printf "      - \"ministryofjustice/data-platform-core-infra\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"

  done

done
