#!/usr/bin/env bash

DEPENDABOT_CONFIGURATION_FILE=".github/dependabot.yml"

echo "Generating ${DEPENDABOT_CONFIGURATION_FILE}"
cat >"${DEPENDABOT_CONFIGURATION_FILE}" <<EOL
---
# This file is auto-generated by running the below command, do not manually amend.
# bash scripts/dependabot/configuration-generator.sh

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ":dependabot: github-actions"
      include: "scope"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ":dependabot: devcontainers"
      include: "scope"

EOL

echo "=== Ecosystem: terraform ==="

SEARCH_PATTERN=".terraform.lock.hcl"
SKIP_FILE=".dependabot-terraform-ignore"

printf "  - package-ecosystem: \"terraform\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "    schedule:\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "      interval: \"daily\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "      time: \"09:00\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "      timezone: \"Europe/London\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "    cooldown:\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "      default-days: 7\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "    open-pull-requests-limit: 15\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "    commit-message:\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "      prefix: \":dependabot: terraform\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "      include: \"scope\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
printf "    directories:\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"

folders=$(find . -type f -name "${SEARCH_PATTERN}" -exec dirname {} \; | LC_ALL=C sort | uniq | cut -c 3-)
export folders

echo "=== Folders ==="
echo "${folders}"

for folder in ${folders}; do
  if [[ -f "${folder}/${SKIP_FILE}" ]]; then
    echo "Ignoring ${folder}"
    continue
  fi
  printf "      - \"${folder}\"\n" >>"${DEPENDABOT_CONFIGURATION_FILE}"
done
