#!/usr/bin/env bash

MODE="${1}"

case ${MODE} in
  containers)
    PATH_FILTER_CONFIGURATION_FILE=".github/path-filter/containers.yml"
    SEARCH_PATTERN="*Dockerfile*"
    SKIP_FILE=".containers-path-filter-ignore"
  ;;
  terraform)
    PATH_FILTER_CONFIGURATION_FILE=".github/path-filter/terraform.yml"
    SEARCH_PATTERN=".terraform.lock.hcl"
    SKIP_FILE=".terraform-path-filter-ignore"
  ;;
  *)
    echo "Usage: ${0} [containers|terraform]"
    exit 1
  ;;
esac

folders=$(find . -type f -name "${SEARCH_PATTERN}" -exec dirname {} \; | sort -h | uniq | cut -c 3-)
export folders

echo "=== Folders ==="
echo "${folders}"

echo "Generating ${PATH_FILTER_CONFIGURATION_FILE}"
cat >"${PATH_FILTER_CONFIGURATION_FILE}" <<EOL
---
# This file is auto-generated by the file below, do not manually amend.
# scripts/path-filter/terraform-generator.sh

EOL

for folder in ${folders}; do

  if [[ -f "${folder}/${SKIP_FILE}" ]]; then
    echo "Ignoring ${folder}"
    continue
  fi

  if [[ "${MODE}" == "terraform" ]]; then
    baseName=$(echo "${folder}" | sed 's|/|-|g' | sed 's|terraform-||')
  else
    baseName=$(basename "${folder}")
  fi

  printf "${baseName}: ${folder}/**\n" >>"${PATH_FILTER_CONFIGURATION_FILE}"
done

if [[ "${GITHUB_ACTIONS}" == "true" ]]; then
  if git diff --exit-code ${PATH_FILTER_CONFIGURATION_FILE} > /dev/null 2>&1; then
    echo "No difference in files, exiting."
    exit 0
  else
    git diff ${PATH_FILTER_CONFIGURATION_FILE}

    mainSha=$(gh api --method GET /repos/"${GITHUB_REPOSITORY}"/contents/"${PATH_FILTER_CONFIGURATION_FILE}" --field ref="main" | jq -r '.sha')
    branchSha=$(gh api --method GET /repos/"${GITHUB_REPOSITORY}"/contents/"${PATH_FILTER_CONFIGURATION_FILE}" --field ref="${GITHUB_HEAD_REF}" | jq -r '.sha')

    if [[ "${branchSha}" != "${mainSha}" ]]; then
      echo "Branch has already been updated, using branch data"
      export apiFieldSha="${branchSha}"
    else
      echo "Branch has not been updated, using main data"
      export apiFieldSha="${mainSha}"
    fi

    gh api --method PUT /repos/${GITHUB_REPOSITORY}/contents/${PATH_FILTER_CONFIGURATION_FILE} \
      --field branch="${GITHUB_HEAD_REF}" \
      --field message="Committing updated path-filter configuration" \
      --field encoding="base64" \
      --field content="$( base64 -w 0 ${PATH_FILTER_CONFIGURATION_FILE} )" \
      --field sha="${apiFieldSha}"
  fi
else
  echo "Not running in GitHub Actions, exiting."
  exit 0
fi
