apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-engg-support-assistant-ingress
  namespace: ${KUBE_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 35.176.93.186/32, 51.149.250.0/23, 51.149.249.0/29, 194.33.249.0/29, 51.149.249.32/29, 194.33.248.0/29, 20.49.214.199/32, 20.49.214.228/32, 51.149.249.35/32, 128.77.75.64/26
    external-dns.alpha.kubernetes.io/set-identifier: data-engg-support-assistant-ingress-${KUBE_NAMESPACE}-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
  - hosts:
    - ${KUBE_NAMESPACE}.apps.live.cloud-platform.service.justice.gov.uk
  rules:
  - host: ${KUBE_NAMESPACE}.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: data-engg-support-assistant-svc
            port:
              number: 8501