---
name: Charts

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/charts.yml
      - charts/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/charts.yml
      - charts/**

permissions: read-all

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      charts: ${{ steps.detect_changes.outputs.changes }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build path-filters file
        id: build_path_filters
        run: bash scripts/path-filter/configuration-generator.sh charts

      - name: Detect changes
        id: detect_changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        with:
          filters: .github/path-filter/charts.yml

  chart-workflow:
    if: ${{ needs.detect-changes.outputs.charts != '[]' }}
    needs: [detect-changes]
    name: Reusable Workflow
    permissions:
      contents: read
      id-token: write
      packages: write
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(needs.detect-changes.outputs.charts) }}
    uses: ./.github/workflows/reusable-workflow-charts.yml
    with:
      chart: ${{ matrix.chart }}
    secrets: inherit
