name: Check for broken links

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"

permissions: read-all

jobs:
  check_links:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v3
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3
      - name: htmlproofer
        run: /scripts/check-url-links.sh
