---
name: ":dependabot: Dependabot Configuration Generator"

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependabot-configuration-generator:
    name: Dependabot Configuration Generator
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Dependabot Configuration Generator
        id: run_dependabot_configuration_generator
        run: |
          bash scripts/dependabot/configuration-generator.sh

      - name: Detect Changes in .github/dependabot.yml
        id: detect_changes
        run: |
          git diff --quiet --exit-code .github/dependabot.yml
        continue-on-error: true

      - name: Commit Changes
        id: commit_changes
        uses: planetscale/ghcommit-action@5b20c92facae8dbf8a3836dc65b8503dda378573 # v0.2.13
        with:
          commit_message: "🤖 Update .github/dependabot.yml"
          file_pattern: ".github/dependabot.yml"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.DATA_PLATFORM_ROBOT_TOKEN }}
