---
name: 📥 Create Ingestion Maintenance Patching Issue

on:
  schedule:
    - cron: "0 8 1,15 * *" # UTC time: “At 08:00 on day-of-month 1 and 15.”
    
permissions: {}

jobs:
  create-issue:
    name: Create Patching Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Patching Issue
        id: create_issue
        run: |
          if [[ "${CLOSE_PREVIOUS}" == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: 📥 Ingestion Maintenance Patching
          ASSIGNEES:
          LABELS: story
          BODY: |
            ### User Story

            As a… engineer on the Analytical Platform
            I need/want/expect to… keep the ingestion service up to date
            So that… security / best practice etc

            ### Definition of Done
            - [ ] Merge any open depenabot Pull Requests in the ingestion repositories (noted below)
            - [ ] Create new release of [ingestion-transfer](https://github.com/ministryofjustice/analytical-platform-ingestion-transfer/releases)
            - [ ] Create new release of [ingestion-scan ](https://github.com/ministryofjustice/analytical-platform-ingestion-scan/releases)
            - [ ] Create new release of [ingestion-notify](https://github.com/ministryofjustice/analytical-platform-ingestion-notify/releases/tag/0.0.14)
            - [ ] Update the images used in the Modernisation Platform environments repository (in the manner done [here](https://github.com/ministryofjustice/modernisation-platform-environments/commit/af4d5003385721502127e5a8c22d0a21eee492fa))
            - [ ] Deploy development
            - [ ] Deploy production

          PINNED: false
          CLOSE_PREVIOUS: false
