---
name: Platform - PagerDuty Slack On-Call

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 8 * * 1-5" # Monday-Friday at 08:00 UTC
  workflow_dispatch:

permissions: read-all

jobs:
  pagerduty-slack-on-call:
    name: PagerDuty Slack On-Call
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: scripts/pagerduty/slack-on-call
    strategy:
      matrix:
        include:
          # Commenting out Analytical Platform for now as it's not being used
          # - pagerduty-schedule-id: P2IZGH3 # Analytical Platform
          #   slack-channel: C58G63XK5 # analytical-platform
          - pagerduty-schedule-id: POE95CC # Data Platform
            slack-channel: C04BRGD7KFH # data-platform-core-infrastructure-team
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
        with:
          python-version: 3.9

      - name: Install requirements
        id: install_requirements
        run: |
          pip install --requirement requirements.txt

      - name: Configure AWS Credentials
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::042130406152:role/GlobalGitHubActionAccess

      - name: Assume GlobalGitHubActionAdmin Role
        id: assume_global_github_action_admin_role
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::042130406152:role/GlobalGitHubActionAdmin
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          role-skip-session-tagging: true

      - name: Get AWS Secrets
        id: get_aws_secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@8b74ff84db6163db54c6c42ed90b0b9f2bc8a60a # v1.0.3
        with:
          secret-ids: |
            PAGERDUTY_TOKEN, pagerduty-token
            SLACK_TOKEN, slack-pagerduty-on-call-token

      - name: Run scripts/pagerduty/slack-on-call.sh
        id: run_slack_on_call
        run: |
          python main.py
        env:
          PAGERDUTY_SCHEDULE_ID: ${{ matrix.pagerduty-schedule-id }}
          PAGERDUTY_TOKEN: ${{ env.PAGERDUTY_TOKEN }}
          SLACK_CHANNEL: ${{ matrix.slack-channel }}
          SLACK_TOKEN: ${{ env.SLACK_TOKEN }}
