---
name: 🦝 Super Linter

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@9e604949e842733e0990f5eb6627844e8715deeb # v6.4.0
    with:
      # VALIDATE_KUBERNETES_KUBECONFORM is set to false as it cannot process Helm charts
      # VALIDATE_PYTHON_* are set to false as we need to revisit the Python from a linting perspective
      super-linter-variables: |
        {
          "DEFAULT_BRANCH": "main",
          "VALIDATE_ALL_CODEBASE": false,
          "FILTER_REGEX_EXCLUDE": ".*archive/.*",
          "VALIDATE_BASH": false,
          "VALIDATE_BASH_EXEC": false,
          "VALIDATE_SHELL_SHFMT": false,
          "VALIDATE_HTML": false,
          "VALIDATE_JAVASCRIPT_STANDARD": false,
          "VALIDATE_OPENAPI": false,
          "VALIDATE_KUBERNETES_KUBECONFORM": false,
          "VALIDATE_TERRAFORM_TERRASCAN": false,
          "VALIDATE_CHECKOV": false,
          "VALIDATE_JSCPD": false,
          "VALIDATE_CSS": false,
          "VALIDATE_GITHUB_ACTIONS": false,
          "PYTHON_ISORT_CONFIG_FILE": "pyproject.toml",
          "VALIDATE_TRIVY": false
        }
