---
name: ✍️ Check Commit Signatures

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Check Commit Signatures
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-commit-signature-checker.yml@497b26456c1f0cff118cf5f663b66794d368f3e8 # v8.0.2
