---
name: Pull request staler

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 1 * * *"

permissions: read-all

jobs:
  pull-request-staler:
    name: Pull request staler
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Pull request staler
        id: pull_request_staler
        uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
        with:
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-message: "This pull reuest is being marked as stale because it has been open for 30 days with no activity. Remove stale label or comment to keep the pull reuest open."
          close-pr-message: "This pull reuest is being closed because it has been open for a further 7 days with no activity. If this is still a valid pull reuest, please reopen it, Thank you!"
          stale-pr-label: "stale"
          exempt-pr-labels: "do-not-stale"
