---
name: Create epic label

on: # yamllint disable-line rule:truthy
  issues:
    types:
      - labeled

concurrency:
  group: create-epic-label
  cancel-in-progress: true

permissions: read-all

jobs:
  create-epic-label:
    if: github.event.label.name == 'Epic'
    name: Create epic label
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create epic label
        id: create_epic_label
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = context.payload.issue.title;
            const issueNumber = context.payload.issue.number;
            const labelName = `${issueTitle} (Epic #${issueNumber})`;
            const labels = context.payload.issue.labels;

            // Generate a random 6-digit hexadecimal color
            const randomColor = Math.floor(Math.random()*16777215).toString(16);

            // Check if label already exists
            const existingLabels = await github.paginate(github.rest.issues.listLabelsForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            if (!existingLabels.find(label => label.name === labelName)) {
              // Label doesn't exist, create it
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: labelName,
                color: randomColor
              });
            }
