---
name: 🦝 Super Linter

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@497b26456c1f0cff118cf5f663b66794d368f3e8 # v8.0.2
    with:
      # VALIDATE_KUBERNETES_KUBECONFORM is set to false as it cannot process Helm charts
      super-linter-variables: |
        {
          "DEFAULT_BRANCH": "main",
          "ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT": false,
          "VALIDATE_ALL_CODEBASE": false,
          "FILTER_REGEX_EXCLUDE": ".*archive/.*",
          "VALIDATE_BASH": false,
          "VALIDATE_BASH_EXEC": false,
          "VALIDATE_SHELL_SHFMT": false,
          "VALIDATE_HTML": false,
          "VALIDATE_JAVASCRIPT_STANDARD": false,
          "VALIDATE_OPENAPI": false,
          "VALIDATE_KUBERNETES_KUBECONFORM": false,
          "VALIDATE_TERRAFORM_TERRASCAN": false,
          "VALIDATE_CHECKOV": false,
          "VALIDATE_JSCPD": false,
          "VALIDATE_CSS": false,
          "VALIDATE_GITHUB_ACTIONS": false,
          "VALIDATE_PYTHON_RUFF_FORMAT": false,
          "PYTHON_ISORT_CONFIG_FILE": "pyproject.toml"
        }
