---
name: ✍️ Check Commit Signatures

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Check Commit Signatures
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-commit-signature-checker.yml@c1b4db7eb29e6b9599a9919c92a5182be2a03306 # v6.3.0
