---
name: ✍️ Check Commit Signatures

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Check Commit Signatures
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-commit-signature-checker.yml@8465086d84a8ae8fb993ef582f00cf13b8ceb9c8 # v7.1.0
