---
name: Generate Dependabot configuration

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/repository-generate-dependabot-configuration.yml
      - 'scripts/dependabot/**'
  schedule:
    - cron: "30 6 * * 1"
  workflow_dispatch:

permissions: read-all

jobs:
  generate-dependabot-configuration:
    name: Generate Dependabot configuration
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Generate configuration
        id: generate_configuration
        run: bash scripts/dependabot/generate-configuration.sh

      - name: Commit configuration
        id: commit_configuration
        run: bash scripts/dependabot/commit-configuration.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
