---
name: Dependency review

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: read-all

jobs:
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Dependency review
        id: dependency_review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: critical
