name: Secret expiry check

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  check-secret-expiry:
    name: Check secret expiry
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::042130406152:role/github-actions-secret-check
          aws-region: eu-west-2

      - name: Check secret expiry dates
        run: |
          for region in eu-west-1 eu-west-2; do
            echo "Secrets in ${region}:"
            aws secretsmanager list-secrets \
              --region "${region}" \
              --query 'SecretList[*].[Name,ARN,Tags]' \
              --output json
          done
