name: Secret expiry check

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  check-secret-expiry:
    name: Check secret expiry
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::042130406152:role/github-actions-secret-check
          aws-region: eu-west-2

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install boto3

      - name: Check secret expiry dates
        run: python scripts/secret-scan/check_secret_expiry.py
