---
name: Terraform - GitHub - Application Migration

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/terraform-github.yml
      - terraform/github/application-migration/**
      - terraform/github/modules/**
      - configuration/ap_migration_apps.json
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform-github.yml
      - terraform/github/application-migration/**
      - terraform/github/modules/**
      - configuration/ap_migration_apps.json

permissions: read-all

jobs:
  terraform:
    name: Terraform
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      working-directory: terraform/github/application-migration
      aws-role-to-assume: arn:aws:iam::042130406152:role/GlobalGitHubActionAccess
      terraform-version: 1.4.5
      terraform-backend-config-role: arn:aws:iam::042130406152:role/GlobalGitHubActionAdmin
    secrets: inherit
