name: Test Data Platform Catalogue Python library

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - python-libraries/data-platform-catalogue/**
  push:
    branches:
      - main
    paths:
      - python-libraries/data-platform-catalogue/**

permissions: read-all

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-libraries/data-platform-catalogue
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version:
          - "3.10"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Poetry
        id: install_poetry
        run: |
          curl -sSL "https://install.python-poetry.org" | python3 -
          echo "${HOME}/.poetry/bin" >>"${GITHUB_PATH}"

      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: python-libraries/data-platform-catalogue/poetry.lock

      - name: Poetry install
        id: poetry_install
        run: |
          poetry install

      - name: Run tests
        id: run_tests
        run: |
          poetry run pytest
