name: Test Data Platform Catalogue Python library

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - python-libraries/data-platform-catalogue/**
  push:
    branches:
      - main
    paths:
      - python-libraries/data-platform-catalogue/**

permissions: read-all

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-libraries/data-platform-catalogue
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version:
          - "3.10"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Poetry
        id: install_poetry
        run: |
          curl -sSL "https://install.python-poetry.org" | python3 -
          echo "${HOME}/.poetry/bin" >>"${GITHUB_PATH}"

      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: python-libraries/data-platform-catalogue/poetry.lock

      - name: Poetry install
        id: poetry_install
        run: |
          poetry install

      - name: Run tests
        id: run_tests
        run: |
          poetry run pytest
