name: Test PAT (ghcommit-action)

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test-pat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Make a change but DO NOT git commit it; the action will do that
      - name: Make a trivial change
        run: |
          echo "last tested: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> PAT_TEST.md

      - name: Commit via planetscale/ghcommit-action using PAT
        uses: planetscale/ghcommit-action@322be9669498a4be9ce66efc1169f8f43f6bd883 # v0.2.17
        with:
          commit_message: "Test commit via PAT"
          file_pattern: "PAT_TEST.md"
          repo: ${{ github.repository }}
          # Push to a scratch branch so you don't touch protected branches
          branch: pat-test-branch
        env:
          # Your fine-grained PAT stored as a secret
          GITHUB_TOKEN: ${{ secrets.AP_DEPENDABOT_COMMIT_TOKEN }}

